vg:
  - name: <vg name>
    device:                 # 根据该值判断是否创建 PV 以及扩容 VG
      - <device>
      - <device>
    thin_pool:               # 根据该值判断是否需要扩容 thin pool
      name: <thin_pool name>
      size: <size>